---
- name: OS Pre-reqs for Dev Portal
  hosts: "{{ target_hosts }}"
  gather_facts: no
  tags: ['os-pre-req']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  vars:
    php_packages:
    - php
    - php-cli
    - php-common
    - php-gd
    - php-mbstring
    - php-mysql
    - php-pdo
    - php-pear
    - php-pecl-apc
    - php-process
    - php-xml
  tasks:
  - name: Remove pre-exisiting PHP packages
    tags: ['dp-os-php-pre-req']
    ignore_errors: yes
    yum:
      name: "{{ item }}"
      state: absent
    with_items: "{{ php_packages }}"
