---
- name: Configure Management Server for TLS
  hosts: ms
  become: yes
  become_user: apigee
  tags: ['ms']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  vars:
    cwc_properties:
    - { key: 'conf_virtualhost_virtual.host.properties.names', value: 'proxy_read_timeout,keepalive_timeout,ssl_ciphers,ssl_protocols,proxy_request_buffering,proxy_buffering,listen', file_name: 'management-server' }
  roles:
  - { role: apigee-opdk-setup-default-settings, tags:['cache'] }
  - apigee-opdk-cwc-update
  - apigee-opdk-stop-components
  - apigee-opdk-start-components

- name: Configure Each Router for TLS
  hosts: r
  become: yes
  become_user: apigee
  tags: ['router']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  vars:
    cwc_properties:
    - { key: 'conf_virtualhost_virtual.host.properties.names', value: 'proxy_read_timeout,keepalive_timeout,ssl_ciphers,ssl_protocols,proxy_request_buffering,proxy_buffering,listen', file_name: 'management-server' }
  roles:
  - apigee-opdk-setup-default-settings
  - apigee-opdk-cwc-update
  - apigee-opdk-stop-components
  - apigee-opdk-start-components

- name: Update VHOST Configuration
  hosts: ms
  tags: ['vhost']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  vars:
    org_name: opdk
    env_name: test
    vhost_name: secure
    vhost_port: 9001
    vhost_alias: "10.142.0.11:9443 10.142.0.13:9443"

  tasks:
  - name: Update VHOST Configuration
    uri:
      url: "http://{{ local_mgmt_ip }}:8080/v1/o/{{ org_name }}/environements/{{ env_name }}/virtualhosts/{{ vhost_name }}"
      method: POST
      user: "{{ opdk_user_name }}"
      password: "{{ opdk_user_password }}"
      force_basic_auth: yes
      headers:
        Content-Type: "application/xml"
      body: |
        <VirtualHost name='{{ vhost_name }}'>
             <Port>'{{ vhost_port }}'</Port>
             <HostAliases>
                 <HostAlias>'{{ vhost_alias }}'</HostAlias>
             </HostAliases>
             <Properties>
                 <Property name='listen'>{{vhost_alias }}</Property>
             </Properties>
         </VirtualHost>

