---

- name: "Check message port ports for rmp hosts"
  hosts: rmp
  roles:
  - apigee-internal-port-connectivity-validator-mp

- name: "Check message port ports for mp hosts"
  hosts: mp
  roles:
  - apigee-internal-port-connectivity-validator-mp

- name: "Check ldap ports for ldap hosts"
  hosts: ldap
  roles:
  - apigee-internal-port-connectivity-validator-ldap

- name: "Check cassandra ports for ds hosts"
  hosts: ds
  roles:
  - apigee-internal-port-connectivity-validator-cassandra

- name: "Check zookeeper ports for zk hosts"
  hosts: ds
  roles:
  - apigee-internal-port-connectivity-validator-zookeeper

- name: "Check management server ports for ms hosts"
  hosts: ms
  roles:
  - apigee-internal-port-connectivity-validator-ms

- name: "Check postgres ports for pg hosts"
  hosts: pg
  roles:
  - apigee-internal-port-connectivity-validator-postgres

- name: "Check router ports for rmp hosts"
  hosts: rmp
  roles:
  - apigee-internal-port-connectivity-validator-router

- name: "Check router ports for r hosts"
 hosts: r
  roles:
  - apigee-internal-port-connectivity-validator-router

- name: "Check qpid ports for qpid hosts"
  hosts: qpid
  roles:
  - apigee-internal-port-connectivity-validator-qpid

- name: "Check ui ports for ui hosts"
  hosts: ui
  roles:
  - apigee-internal-port-connectivity-validator-ui
