---
- name: Setup Qpid on dc-1
  hosts: "{{ target_hosts }}"
  gather_facts: no
  tags: ['qpid']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  roles:
  - { role: apigee-opdk-setup-component, profile: 'qs',tags: ['apigee-component']  }

  tasks:
  - block:

    - name: Install Apigee Qpid Component
      tags: ['apigee-component']
      import_role:
        name: apigee-opdk-setup-component
      vars:
        profile: 'qs'

    rescue:
      - name: Use Apigee Qpid Work Around
        shell: yum --setopt=obsoletes=0 install apigee-qpidd

      - name: Install Apigee Qpid Component
        tags: ['apigee-component']
        import_role:
          name: apigee-opdk-setup-component
        vars:
          profile: 'qs'


  - name: Start Apigee Qpid Component
    tags: ['self']
    import_role:
      name: apigee-opdk-start-components
    vars:
      server_types: ['qs']


  - name: Collect Self Report for Apigee Qpid
    tags: ['self']
    import_role:
      name: apigee-opdk-server-self
    vars:
      server_types: ['qs']

  - name: Assert Setup Status
    tags: ['status']
    import_role:
      name: apigee-opdk-setup-status
