---
- name: Update planet cache
  tags: ['cache']
  import_playbook: apigee-planet-cache.yml
  vars:
    target_hosts: ms,sso

- name: Install and configure Openldap pre-requisites
  import_playbook: apigee-os-pre-requisites-epel.yml
  tags: ['os', 'os-epel']
  vars:
    target_hosts: sso

- name: Install and configure OS pre-requisites
  import_playbook: apigee-os-pre-requisites.yml
  tags: ['os']
  vars:
    target_hosts: sso

- name: Install and configure Pip pre-requisites
  import_playbook: apigee-os-pre-requisites-pip.yml
  tags: ['os', 'os-pip']
  vars:
    target_hosts: sso

- name: Install Apigee pre-requisites
  import_playbook: apigee-pre-requisites-bootstrap.yml
  tags: ['bootstrap']
  vars:
    target_hosts: sso

- name: Install Apigee pre-requisites
  import_playbook: apigee-pre-requisites-common-install.yml
  tags: ['common']
  vars:
    target_hosts: sso

- name: Install Edge SSO
  hosts: sso,ms
  gather_facts: no
  tags: ['sso-config']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  roles:
  - { role: apigee-opdk-setup-component-install, component: 'apigee-ssoadminapi' }
  - { role: apigee-opdk-setup-edge-sso-config, tags: ['sso-config'] }
  - { role: apigee-opdk-setup-apigee-user-ownership, tags: ['apigee-user'] }

- name: Install Postgres
  hosts: sso-pg
  gather_facts: no
  serial: 1
  tags: ['pg']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  roles:
  - { role: apigee-opdk-setup-component, profile: 'ps', opdk_installation_config_file: "{{ edge_sso_installation_config_file }}", tags: ['apigee-component'] }
  - { role: apigee-opdk-start-components, tags: ['apigee-component'] }
  - { role: apigee-opdk-server-self, server_types: ['ps'], tags: ['self']  }
  - { role: apigee-opdk-setup-status, tags: ['status'] }



- name: Install Edge SSO
  hosts: sso,ms
  become: true
  become_user: "{{ opdk_user_name }}"
  gather_facts: no
  tags: ['sso']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  roles:
  - { role: apigee-opdk-setup-component, profile: 'sso', opdk_installation_config_file: "{{ edge_sso_installation_config_file }}", tags: ['sso-setup']  }

