---
- name: Setup RMP on dc-1
  hosts: "{{ target_hosts }}"
  gather_facts: no
  tags: ['mp']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  roles:
  - { role: apigee-opdk-setup-component, profile: 'mp', tags: ['apigee-component']  }
  - { role: apigee-opdk-start-components, tags: ['apigee-component'] }
  - { role: apigee-opdk-server-self, server_types: ['mp'], tags: ['self']  }
  - { role: apigee-opdk-setup-status, tags: ['status'] }
