---
- name: Upgrade Cassandra
  hosts: ds
  become: true
  become_user: "apigee"
  serial: 1
  tags: ['ds']
  gather_facts: no
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Assert upgrade_from_opdk_version
    fail:
      msg: "Please set the upgrade_from_opdk_version."
    when: "upgrade_from_opdk_version is not defined"

  - name: Report current node
    debug:
      msg: "Upgrading component cs,zk on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}", tags: ['upgrade-ds-config'] }
  - { role: apigee-opdk-update-component, component: 'cs,zk', tags: ['upgrade-ds'] }

- name: Upgrade Qpid
  hosts: qpid
  become: true
  become_user: "apigee"
  serial: 1
  gather_facts: no
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  tags: ['upgrade-qpid']
  pre_tasks:
  - name: Assert upgrade_from_opdk_version
    fail:
      msg: "Please set the upgrade_from_opdk_version."
    when: "upgrade_from_opdk_version is not defined"

  - name: Report current node
    debug:
      msg: "Upgrading component qpid on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}", tags: ['qpid-config']}
  - { role: apigee-opdk-set-reachable, reachability: False, server_types: ['qs'], tags: ['qpid-reachability-false'] }
  - { role: apigee-opdk-iptables-port-block, destination_port: '{{ qpid_messaging_port }}', tags: ['qpid-port-block'] }
  - { role: apigee-opdk-update-component,  component: 'qpid', tags: ['qpid-upgrade'] }
  - { role: apigee-opdk-iptables-flush, tags: ['qpid-iptables-flush'] }
  - { role: apigee-opdk-set-reachable, reachability: True, server_types: ['qs'], tags: ['qpid-reachability-true'] }

- name: Upgrade Postgres
  hosts: pg
  become: true
  become_user: "apigee"
  tags: ['upgrade-pg']
  serial: 1
  gather_facts: no
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Assert upgrade_from_opdk_version
    fail:
      msg: "Please set the upgrade_from_opdk_version."
    when: "upgrade_from_opdk_version is not defined"

  - name: Report current node
    debug:
      msg: "Upgrading component qpid on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-set-reachable, reachability: False, server_types: ['ps'], tags: ['ps-reachability-false'] }
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}", tags: ['pg-config'] }
  - { role: apigee-opdk-update-component,  component: 'ps', validate_ready: false, ignore_errors: true, tags: ['ps-upgrade'] }
  - { role: apigee-opdk-set-reachable, reachability: True, server_types: ['ps'], tags: ['ps-reachability-true'] }

- name: Upgrade Ldap
  hosts: ldap
  become: true
  become_user: "apigee"
  tags: ['upgrade-ldap']
  serial: 1
  gather_facts: no
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Assert upgrade_from_opdk_version
    fail:
      msg: "Please set the upgrade_from_opdk_version."
    when: "upgrade_from_opdk_version is not defined"

  - name: Report current node
    debug:
      msg: "Upgrading component ldap on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}", tags: ['ldap-config'] }
  - { role: apigee-opdk-update-component, component: 'ldap', tags: ['ldap-upgrade'] }

- name: Upgrade Qpid Edge Components
  hosts: qpid
  become: true
  become_user: "apigee"
  serial: 1
  gather_facts: no
  tags: ['upgrade-qpid-edge']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Assert upgrade_from_opdk_version
    fail:
      msg: "Please set the upgrade_from_opdk_version."
    when: "upgrade_from_opdk_version is not defined"

  - name: Report current node
    debug:
      msg: "Upgrading component edge on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-update-component, component: 'edge', tags: ['qpid-edge-upgrade'] }

- name: Upgrade Management Server Edge Components
  hosts: ms
  become: true
  become_user: "apigee"
  serial: 1
  gather_facts: no
  tags: ['upgrade-ms-edge']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Assert upgrade_from_opdk_version
    fail:
      msg: "Please set the upgrade_from_opdk_version."
    when: "upgrade_from_opdk_version is not defined"

  - name: Report current node
    debug:
      msg: "Upgrading component edge on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-update-component,  component: 'edge', tags: ['ms-edge-upgrade'] }

- name: Upgrade Router & Message Processor
  hosts: rmp
  become: true
  become_user: "apigee"
  serial: 1
  gather_facts: no
  tags: ['upgrade-rmp']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Assert upgrade_from_opdk_version
    fail:
      msg: "Please set the upgrade_from_opdk_version."
    when: "upgrade_from_opdk_version is not defined"

  - name: Report current node
    debug:
      msg: "Upgrading component edge on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}", tags: ['rmp-config'] }
  - { role: apigee-opdk-set-reachable, reachability: False, server_types: ['router', 'mp'], tags: ['rmp-reachability-false'] }
  - { role: apigee-opdk-update-component, component: 'edge', tags: ['rmp-upgrade'] }
  - { role: apigee-opdk-set-reachable, reachability: True, server_types: ['router', 'mp'], tags: ['rmp-reachability-true'] }
  tasks:
  - name: Remove router configuration directory
    tags: ['rmp-config-refresh']
    file:
      path: '/opt/nginx/config.d'
      state: absent

  - name: Restore router configuration directory
    tags: ['rmp-config-refresh']
    file:
      path: '/opt/nginx/config.d'
      state: directory
      mode: 0755
      owner: "apigee"
      group: "apigee"

  - name: Restart router
    tags: ['rmp-config-refresh']
    command: "/opt/apigee/apigee-service/bin/apigee-service edge-router restart"

- name: Upgrade UI
  hosts: ui
  become: true
  become_user: "apigee"
  serial: 1
  gather_facts: no
  tags: ['ui']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Assert upgrade_from_opdk_version
    fail:
      msg: "Please set the upgrade_from_opdk_version."
    when: "upgrade_from_opdk_version is not defined"

  - name: Report current node
    debug:
      msg: "Upgrading component ui on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}" }
  - { role: apigee-opdk-update-component,  component: 'ui', tags: ['ui-upgrade'] }

- name: Validate RMP
  import_playbook: install-edge-rmp-validate.yml
  tags: ['validate']
  vars:
    target_hosts: rmp

#- name: Upgrade PG in dc-1
#  include: upgrade-edge-postgres.yml
#  tags: ['pg']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-1-ds
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-2-ds
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-1-ms
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-2-ms
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-1-rmp
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-2-rmp
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-1-qpid
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-2-qpid
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-1-pgmaster
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-2-pgmaster
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-1-pgstandby
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-2-pgstandby
  tags: ['logs']
