---
- name: Update planet cache
  import_playbook: apigee-planet-cache.yml
  vars:
    target_hosts: planet

- name: Update prequisites
  hosts: ds,ms,rmp,qpid,pg
  serial: 1
  tags: ['update-pre-req']
  gather_facts: no
  vars_files:
    - ~/.apigee-secure/credentials.yml
    - ~/.apigee/custom-properties.yml
  roles:
  - { role: apigee-opdk-start-components }

- name: Install and configure Apigee bootstrap
  import_playbook: apigee-pre-requisites-bootstrap.yml
  tags: ['bootstrap']
  vars:
    target_hosts: planet
    upgrade_edge: True

- name: Install and configure Apigee common installation
  import_playbook: apigee-pre-requisites-common-update.yml
  tags: ['common']
  vars:
    target_hosts: planet
    upgrade_edge: True

- name: Upgrade Edge instance on planet
  tags: ['upgrade']
  import_playbook: upgrade-edge-planet.yml
