---
- name: Upgrade PS component
  hosts: pgmaster
  become: yes
  become_user: "{{ opdk_user_name }}"
  serial: 1
  gather_facts: no
  tags: ['pgmaster-update']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Report current node
    debug:
      msg: "Upgrading component ps on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-set-reachable, reachability: False, server_types: ['ps'] }
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}" }
  - { role: apigee-opdk-update-component,  component: 'ps', validate_ready: false, ignore_errors: true}
  - { role: apigee-opdk-start-components }
  - { role: apigee-opdk-setup-postgres-db-upgrade }
  - { role: apigee-opdk-start-components }
  - { role: apigee-opdk-set-reachable, reachability: True, server_types: ['ps'] }

- name: Upgrade PS edge component
  hosts: pgmaster
  become_user: "{{ opdk_user_name }}"
  serial: 1
  gather_facts: no
  tags: ['pgmaster-edge']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Report current node
    debug:
      msg: "Upgrading component edge on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-set-reachable, reachability: False, server_types: ['ps'] }
  - { role: apigee-opdk-update-component,  component: 'edge', validate_ready: false, ignore_errors: true, tags: ['pgmaster-edge-upgrade'] }

- name: Upgrade Postgres standby
  hosts: pgstandby
  become_user: "{{ opdk_user_name }}"
  serial: 1
  gather_facts: no
  tags: ['pgstandby']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Report current node
    debug:
      msg: "Upgrading component ps on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}" }
  - { role: apigee-opdk-stop-components, component_name: 'apigee-postgresql' }
  - { role: apigee-opdk-setup-postgres-config, tags: ['os-pre-req'], clear_pgdata: True }
  - { role: apigee-opdk-update-component,  component: 'ps', validate_ready: false, ignore_errors: true, tags: ['pgstandby-upgrade'] }
  - { role: apigee-opdk-set-reachable, reachability: True, server_types: ['ps'] }

#- name: Start Qpid components
#  hosts: qpid
#  become_user: "{{ opdk_user_name }}"
#  tags: ['qpid-start']
#  vars_files:
#  - ~/.apigee-secure/credentials.yml
#  - ~/.apigee/custom-properties.yml
#  roles:
#  - { role:  apigee-opdk-start-components, component_name: 'edge-qpid-server', component_start_delay: 1 }

- name: Validate that PG Master is master
  hosts: pgmaster
  become_user: "{{ opdk_user_name }}"
  tags: ['pgmaster-validate']
  serial: 1
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  gather_facts: no
  roles:
  - { role: apigee-opdk-start-components }
  tasks:
  - name: Validate this is postgresql master
    shell: "/opt/apigee/apigee-service/bin/apigee-service apigee-postgresql postgres-check-master"

- name: Setup and Validate that PG Standby is standby
  hosts: pgstandby
  become_user: "{{ opdk_user_name }}"
  tags: ['pgstandby-validate']
  gather_facts: no
  serial: 1
  vars:
    cwc_properties:
    - { key: conf_postgresql_max_wal_senders, value: '3', file_name: 'postgresql' }
    - { key: conf_postgresql_wal_keep_segments, value: '500', file_name: 'postgresql' }
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}" }
  - { role: apigee-opdk-start-components }
  - { role: apigee-opdk-setup-postgres-standby }
  - { role: apigee-opdk-cwc-update, when: update_max_wal_settings is defined and update_max_wal_settings }
  - { role: apigee-opdk-stop-components, tags: ['stop'], when: update_max_wal_settings is defined and update_max_wal_settings  }
  - { role: apigee-opdk-start-components, tags: ['start'],  when: update_max_wal_settings is defined and update_max_wal_settings }
  - { role: apigee-opdk-setup-postgres-standby, when: update_max_wal_settings is defined and update_max_wal_settings }

- name: Upgrade PG with edge for remaining components
  hosts: pg
  become_user: "{{ opdk_user_name }}"
  tags: ['pg-edge']
  serial: 1
  gather_facts: no
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Report current node
    debug:
      msg: "Upgrading component edge on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}" }
  - { role: apigee-opdk-update-component,  component: 'edge', validate_ready: false, ignore_errors: true, tags: ['pg-edge-upgrade']  }
