---
- name: Upgrade Cassandra
  hosts: ds
  become: true
  become_user: "apigee"
  serial: 1
  tags: ['ds']
  gather_facts: no
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Assert upgrade_from_opdk_version
    fail:
      msg: "Please set the upgrade_from_opdk_version."
    when: "upgrade_from_opdk_version is not defined"

  - name: Report current node
    debug:
      msg: "Upgrading component cs,zk on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-start-components }
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}", tags: ['upgrade-ds-config'] }
  - { role: apigee-opdk-update-component, component: 'cs,zk', tags: ['upgrade-ds'] }

- name: Upgrade Qpid
  hosts: qpid
  become: true
  become_user: "apigee"
  serial: 1
  tags: ['qpid']
  gather_facts: no
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Assert upgrade_from_opdk_version
    fail:
      msg: "Please set the upgrade_from_opdk_version."
    when: "upgrade_from_opdk_version is not defined"

  - name: Report current node
    debug:
      msg: "Upgrading component qpid on {{ inventory_hostname }} ( {{ ansible_hostname }} )"


  - name: Work around remove for Qpid upgrade
    ignore_errors: yes
    yum:
      name: "{{ item }}"
      state: absent
    with_items:
    - qpid-cpp-server
    - qpid-cpp-server-linearstore
    - qpid-tools qpid-qmf
    - python-qpid
    - qpid-cpp-client
    - qpid-proton-c

  - name: Work around install for Qpid upgrade
    yum:
      name: "{{ item }}"
      state: present
    with_items:
    - yum-plugin-priorities
    - apigee-qpidd

  roles:
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}", tags: ['qpid-config']}
  - { role: apigee-opdk-start-components }
  - { role: apigee-opdk-set-reachable, reachability: False, server_types: ['qs'], tags: ['qpid-reachability-false'] }
  - { role: apigee-opdk-iptables-port-block, destination_port: '{{ qpid_messaging_port }}', tags: ['qpid-port-block'] }
  - { role: apigee-opdk-update-component,  component: 'qpid', tags: ['qpid-upgrade'] }
  - { role: apigee-opdk-iptables-flush, tags: ['qpid-iptables-flush'] }
  - { role: apigee-opdk-set-reachable, reachability: True, server_types: ['qs'], tags: ['qpid-reachability-true'] }

- name: Upgrade Ldap
  hosts: ldap
  become: true
  become_user: "apigee"
  tags: ['ldap']
  serial: 1
  gather_facts: no
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Assert upgrade_from_opdk_version
    fail:
      msg: "Please set the upgrade_from_opdk_version."
    when: "upgrade_from_opdk_version is not defined"

  - name: Report current node
    debug:
      msg: "Upgrading component ldap on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}", tags: ['ldap-config'] }
  - { role: apigee-opdk-update-component, component: 'ldap', tags: ['ldap-upgrade'] }

- name: Upgrade Postgres
  include: upgrade-edge-postgres.yml
  tags: ['pg']

- name: Upgrade Qpid Edge Components
  hosts: qpid
  become: true
  become_user: "apigee"
  serial: 1
  gather_facts: no
  tags: ['qpid-edge']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Assert upgrade_from_opdk_version
    fail:
      msg: "Please set the upgrade_from_opdk_version."
    when: "upgrade_from_opdk_version is not defined"

  - name: Report current node
    debug:
      msg: "Upgrading component edge on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}", tags: ['qpid-edge-config'] }
  - { role: apigee-opdk-start-components }
  - { role: apigee-opdk-update-component, component: 'edge', tags: ['qpid-edge-upgrade'] }

- name: Upgrade Management Server Edge Components
  hosts: ms
  become: true
  become_user: "apigee"
  serial: 1
  gather_facts: no
  tags: ['ms']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Assert upgrade_from_opdk_version
    fail:
      msg: "Please set the upgrade_from_opdk_version."
    when: "upgrade_from_opdk_version is not defined"

  - name: Report current node
    debug:
      msg: "Upgrading component edge on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}", tags: ['ms-config'] }
  - { role: apigee-opdk-update-component,  component: 'edge', tags: ['ms-upgrade'] }
  - { role: apigee-opdk-start-components }

- name: Upgrade Router & Message Processor
  hosts: rmp
  become: true
  become_user: "apigee"
  serial: 1
  gather_facts: no
  tags: ['rmp']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Assert upgrade_from_opdk_version
    fail:
      msg: "Please set the upgrade_from_opdk_version."
    when: "upgrade_from_opdk_version is not defined"

  - name: Report current node
    debug:
      msg: "Upgrading component edge on {{ inventory_hostname }} ( {{ ansible_hostname }} )"

  - name: Upgrade Apigee Nginx
    become: yes
    yum:
      name: apigee-nginx
      state: latest

  roles:
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}", tags: ['rmp-config'] }
  - { role: apigee-opdk-set-reachable, reachability: False, server_types: ['router', 'mp'], tags: ['rmp-reachability-false'] }
  - { role: apigee-opdk-update-component, component: 'edge', tags: ['rmp-upgrade'] }
  - { role: apigee-opdk-set-reachable, reachability: True, server_types: ['router', 'mp'], tags: ['rmp-reachability-true'] }
  tasks:
  - name: Remove router configuration directory
    tags: ['rmp-config-refresh']
    file:
      path: '/opt/nginx/config.d'
      state: absent

  - name: Restore router configuration directory
    tags: ['rmp-config-refresh']
    file:
      path: '/opt/nginx/config.d'
      state: directory
      mode: 0755
      owner: "apigee"
      group: "apigee"

  - name: Restart router
    tags: ['rmp-config-refresh']
    command: "/opt/apigee/apigee-service/bin/apigee-service edge-router restart"

- name: Upgrade Router
  hosts: r
  become: true
  become_user: "apigee"
  serial: 1
  gather_facts: no
  tags: ['r']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Assert upgrade_from_opdk_version
    fail:
      msg: "Please set the upgrade_from_opdk_version."
    when: "upgrade_from_opdk_version is not defined"

  - name: Report current node
    debug:
      msg: "Upgrading component edge on {{ inventory_hostname }} ( {{ ansible_hostname }} )"

  - name: Upgrade Apigee Nginx
    become: yes
    yum:
      name: apigee-nginx
      state: latest

  roles:
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}", tags: ['r-config'] }
  - { role: apigee-opdk-set-reachable, reachability: False, server_types: ['router'], tags: ['r-reachability-false'] }
  - { role: apigee-opdk-update-component, component: 'edge', tags: ['r-upgrade'] }
  - { role: apigee-opdk-set-reachable, reachability: True, server_types: ['router'], tags: ['r-reachability-true'] }
  tasks:
  - name: Remove router configuration directory
    tags: ['r-config-refresh']
    file:
      path: '/opt/nginx/config.d'
      state: absent

  - name: Restore router configuration directory
    tags: ['r-config-refresh']
    file:
      path: '/opt/nginx/config.d'
      state: directory
      mode: 0755
      owner: "apigee"
      group: "apigee"

  - name: Restart router
    tags: ['r-config-refresh']
    command: "/opt/apigee/apigee-service/bin/apigee-service edge-router restart"

- name: Upgrade Message Processor
  hosts: mp
  become: true
  become_user: "apigee"
  serial: 1
  gather_facts: no
  tags: ['mp']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Assert upgrade_from_opdk_version
    fail:
      msg: "Please set the upgrade_from_opdk_version."
    when: "upgrade_from_opdk_version is not defined"

  - name: Report current node
    debug:
      msg: "Upgrading component edge on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}", tags: ['mp-config'] }
  - { role: apigee-opdk-set-reachable, reachability: False, server_types: ['mp'], tags: ['mp-reachability-false'] }
  - { role: apigee-opdk-update-component, component: 'edge', tags: ['mp-upgrade'] }
  - { role: apigee-opdk-set-reachable, reachability: True, server_types: ['mp'], tags: ['mp-reachability-true'] }

- name: Upgrade UI
  hosts: ui
  become: true
  become_user: "apigee"
  serial: 1
  gather_facts: no
  tags: ['ui']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Assert upgrade_from_opdk_version
    fail:
      msg: "Please set the upgrade_from_opdk_version."
    when: "upgrade_from_opdk_version is not defined"

  - name: Report current node
    debug:
      msg: "Upgrading component ui on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}", tags: ['ui-config'] }
  - { role: apigee-opdk-update-component,  component: 'ui', tags: ['ui-upgrade'] }

- name: Validate RMP
  import_playbook: install-edge-rmp-validate.yml
  tags: ['validate']
  vars:
    target_hosts: rmp

#- name: Upgrade PG in dc-1
#  include: upgrade-edge-postgres.yml
#  tags: ['pg']

- name: Rolling restart of dc-1
  hosts: edge
  serial: 1
  tags: ['restart']
  roles:
  - apigee-opdk-stop-components
  - apigee-opdk-start-components

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-1-ds
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-2-ds
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-1-ms
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-2-ms
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-1-rmp
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-2-rmp
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-1-qpid
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-2-qpid
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-1-pgmaster
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-2-pgmaster
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-1-pgstandby
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-2-pgstandby
  tags: ['logs']
