---
- name: Upgrade Cassandra
  hosts: ds
  become: true
  become_user: "{{ opdk_user_name }}"
  serial: 1
  tags: ['ds']
  gather_facts: no
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Assert upgrade_from_opdk_version
    fail:
      msg: "Please set the upgrade_from_opdk_version."
    when: "upgrade_from_opdk_version is not defined"

  - name: Report current node
    debug:
      msg: "Upgrading component cs,zk on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-start-components, tags: ['ds-start'], component_name: 'apigee-cassandra', }
  - { role: apigee-opdk-start-components, tags: ['ds-start'], component_name: 'apigee-zookeeper' }
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}" }
  - { role: apigee-opdk-update-component, component: 'cs,zk', tags: ['ds-upgrade'] }

- name: Upgrade Qpid
  hosts: qpid
  become: true
  become_user: "{{ opdk_user_name }}"
  serial: 1
  gather_facts: no
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  tags: ['qpid']
  pre_tasks:
  - name: Assert upgrade_from_opdk_version
    fail:
      msg: "Please set the upgrade_from_opdk_version."
    when: "upgrade_from_opdk_version is not defined"

  - name: Report current node
    debug:
      msg: "Upgrading component qpid on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-start-components, tags: ['qpid-start'], component_name: 'apigee-qpidd' }
  - { role: apigee-opdk-start-components, tags: ['qpid-start'], component_name: 'edge-qpid-server' }
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}", tags: ['qpid-config']}
  - { role: apigee-opdk-set-reachable, reachability: False, server_types: ['qs'], tags: ['qpid-reachability'] }
  - { role: apigee-opdk-iptables-port-block, destination_port: '{{ qpid_messaging_port }}' }
  - { role: apigee-opdk-update-component,  component: 'qpid', tags: ['qpid-upgrade'] }
  - { role: apigee-opdk-iptables-flush }
  - { role: apigee-opdk-set-reachable, reachability: True, server_types: ['qs'] }

- name: Upgrade Ldap
  hosts: ldap
  become: true
  become_user: "{{ opdk_user_name }}"
  tags: ['ldap']
  serial: 1
  gather_facts: no
  vars:
    hosts: ldap
    upgrade_component: ldap
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Assert upgrade_from_opdk_version
    fail:
      msg: "Please set the upgrade_from_opdk_version."
    when: "upgrade_from_opdk_version is not defined"

  - name: Report current node
    debug:
      msg: "Upgrading component {{ upgrade_component }} on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-start-components, tags: ['ldap-start'], component_name: 'apigee-openldap' }
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}" }
  - { role: apigee-opdk-update-component, component: '{{ upgrade_component }}', tags: ['ldap-upgrade'] }

- name: Upgrade Qpid Edge Components
  hosts: qpid
  become: true
  become_user: "{{ opdk_user_name }}"
  serial: 1
  gather_facts: no
  tags: ['qpid-edge']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Assert upgrade_from_opdk_version
    fail:
      msg: "Please set the upgrade_from_opdk_version."
    when: "upgrade_from_opdk_version is not defined"

  - name: Report current node
    debug:
      msg: "Upgrading component edge on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-start-components, tags: ['qpid-start'], component_name: 'apigee-qpidd' }
  - { role: apigee-opdk-start-components, tags: ['qpid-start'], component_name: 'edge-qpid-server' }
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}" }
  - { role: apigee-opdk-set-reachable, reachability: False, server_types: ['qs'] }
  - { role: apigee-opdk-iptables-port-block, destination_port: '{{ qpid_messaging_port }}' }
  - { role: apigee-opdk-update-component, component: 'edge', tags: ['qpid-edge-upgrade'] }
  - { role: apigee-opdk-iptables-flush }
  - { role: apigee-opdk-set-reachable, reachability: True, server_types: ['qs'] }

- name: Upgrade Management Server Edge Components
  hosts: ms
  become: true
  become_user: "{{ opdk_user_name }}"
  serial: 1
  gather_facts: no
  tags: ['ms-edge']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Assert upgrade_from_opdk_version
    fail:
      msg: "Please set the upgrade_from_opdk_version."
    when: "upgrade_from_opdk_version is not defined"

  - name: Report current node
    debug:
      msg: "Upgrading component edge on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-start-components, tags: ['ms-edge-start'], component_name: 'edge-management-server' }
  - { role: apigee-opdk-start-components, tags: ['ms-edge-start'], component_name: 'edge-ui' }
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}" }
  - { role: apigee-opdk-update-component,  component: 'edge', tags: ['ms-edge-upgrade'] }

- name: Upgrade Router & Message Processor
  hosts: rmp
  become: true
  become_user: "{{ opdk_user_name }}"
  serial: 1
  gather_facts: no
  tags: ['rmp']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Assert upgrade_from_opdk_version
    fail:
      msg: "Please set the upgrade_from_opdk_version."
    when: "upgrade_from_opdk_version is not defined"

  - name: Report current node
    debug:
      msg: "Upgrading component edge on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-start-components, tags: ['r-start'], component_name: 'edge-router' }
  - { role: apigee-opdk-start-components, tags: ['mp-start'], component_name: 'edge-message-processor' }
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}" }
  - { role: apigee-opdk-set-reachable, reachability: False, server_types: ['router', 'mp'] }
  - { role: apigee-opdk-update-component,  component: 'edge', tags: ['rmp-upgrade'] }
  - { role: apigee-opdk-set-reachable, reachability: True, server_types: ['router', 'mp'] }

- name: Upgrade UI
  hosts: ui
  become: true
  become_user: "{{ opdk_user_name }}"
  serial: 1
  gather_facts: no
  tags: ['ui']
  vars_files:
  - ~/.apigee-secure/credentials.yml
  - ~/.apigee/custom-properties.yml
  pre_tasks:
  - name: Assert upgrade_from_opdk_version
    fail:
      msg: "Please set the upgrade_from_opdk_version."
    when: "upgrade_from_opdk_version is not defined"

  - name: Report current node
    debug:
      msg: "Upgrading component ui on {{ inventory_hostname }} ( {{ ansible_hostname }} )"
  roles:
  - { role: apigee-opdk-modules }
  - { role: apigee-opdk-start-components, tags: ['ui-start'] }
  - { role: apigee-opdk-setup-silent-installation-config, opdk_version: "{{ upgrade_from_opdk_version }}" }
  - { role: apigee-opdk-update-component,  component: 'ui', tags: ['ui-upgrade'] }

- name: Upgrade PG in dc-1
  include: upgrade-edge-postgres.yml
  tags: ['pg']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-1-ds
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-2-ds
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-1-ms
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-2-ms
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-1-rmp
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-2-rmp
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-1-qpid
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-2-qpid
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-1-pgmaster
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-2-pgmaster
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-1-pgstandby
  tags: ['logs']

- include: apigee-log-config-files.yml
  vars:
    target_hosts: dc-2-pgstandby
  tags: ['logs']
